In [1]:
import pandas as pd
pd.DataFrame({'Yes':[50, 21], 'No':[131, 2]})

Yes   No
0   50  131
1   21    2

In [2]:
#Входные значения могут быть не только числа, но и строки
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland.']})

Bob           Sue
0    I liked it.  Pretty good.
1  It was awful.        Bland.

In [3]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 
              'Sue': ['Pretty good.', 'Bland.']},
             index=['Product A', 'Product B'])

Bob           Sue
Product A    I liked it.  Pretty good.
Product B  It was awful.        Bland.

In [7]:
d = pd.Series([1, 2, 3, 4, 5])
print(d)
b = pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product A')
print(b)

0    1
1    2
2    3
3    4
4    5
dtype: int64
2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64


In [15]:
wine_reviews = pd.read_csv("../Codir_RPM_-200_+200_start.csv", index_col=0)
wine_reviews.shape
wine_reviews.head

<bound method NDFrame.head of       TSSsite    direction  distance geneID Gene_id  gene_start  \
1          37  codirection      -153   thrL   b0001         190   
2          38  codirection      -152   thrL   b0001         190   
3         148  codirection       -42   thrL   b0001         190   
4         148  codirection      -189   thrA   b0002         337   
5       -6481  codirection       -22   yaaA   b0006       -6459   
...       ...          ...       ...    ...     ...         ...   
9175  4635477  codirection       -44   creA   b4397     4635521   
9176 -4640372  codirection       -66   arcA   b4401    -4640306   
9177 -4640401  codirection       -95   arcA   b4401    -4640306   
9178  4640411  codirection         9   yjjY   b4402     4640402   
9179  4640756  codirection      -186   yjtD   b4403     4640942   

                K1_VCE            K2_VCE            K3_VCE            T1_VCE  \
1     12,9082508474173  10,1730278697205  16,6774071327489                 0   
2    

In [3]:
import numpy as np
my_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)
print(my_array)

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
# Create an array of ones
np.ones((3,4))

# Create an array of zeros
np.zeros((2,3,4),dtype=np.int16)

# Create an array with random values
np.random.random((2,2))

# Create an empty array
np.empty((3,2))

# Create a full array
np.full((2,2),7)

# Create an array of evenly-spaced values
np.arange(10,25,5)

# Create an array of evenly-spaced values
np.linspace(0,2,9)

# Import your data
#x, y, z = np.loadtxt('data.txt', skiprows=1, unpack=True)

x = np.arange(0.0,5.0,1.0)
np.savetxt('test.out', x, delimiter=',')
np.savez('test.out', x, delimiter=',')
np.savez_compressed('test.out', x, delimiter=',')

In [10]:
# Print the number of `my_array`'s dimensions
print(my_array.ndim)

# Print the number of `my_array`'s elements
print(my_array.size)

# Print information about `my_array`'s memory layout
print(my_array.flags)

# Print the length of one array element in bytes
print(my_array.itemsize)

# Print the total consumed bytes by `my_array`'s elements
print(my_array.nbytes)

2
8
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

8
64


In [11]:
# Print the length of `my_array`
print(len(my_array))

# Change the data type of `my_array`
my_array.astype(float)

2


array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [25]:
#BROADCASTING. the dimensions of your arrays need to be compatible

# Initialize `x`
x = np.ones((3,4))

# Check shape of `x`
print(x.shape)

# Initialize `y`
y = np.random.random((5,3,4))

# Check shape of `y`
print(y.shape)

# Add `x` and `y`
x + y

x - y

x*y

x//y
x/y
x%y

(3, 4)
(5, 3, 4)


array([[[0.15041404, 0.08180618, 0.17952066, 0.05832422],
        [0.04340735, 0.00709575, 0.05513557, 0.00965407],
        [0.3444801 , 0.01489261, 0.24954467, 0.05721169]],

       [[0.09824539, 0.38963315, 0.19156676, 0.02297414],
        [0.46893477, 0.14858191, 0.07899506, 0.10424768],
        [0.03634621, 0.1538453 , 0.10942521, 0.31837076]],

       [[0.01977979, 0.31331797, 0.06916677, 0.46186751],
        [0.20974406, 0.0857029 , 0.33201786, 0.25665471],
        [0.21082877, 0.00248853, 0.00978796, 0.00124423]],

       [[0.26325723, 0.22052615, 0.37331048, 0.03449939],
        [0.0666835 , 0.06469101, 0.08817549, 0.46860314],
        [0.03418682, 0.16303995, 0.15564585, 0.13989742]],

       [[0.36531628, 0.3192963 , 0.21354025, 0.10092033],
        [0.03238156, 0.10526927, 0.04593074, 0.43168374],
        [0.22122158, 0.26493259, 0.28577118, 0.34817383]]])

In [29]:
np.logical_or(x,y)
#np.logical_and(x,y)
#np.logical_not(x,y)

array([[[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]])

In [47]:
# Select the element at the 1st index
print(my_array[0:])
print(my_array[my_array<2])

[[1 2 3 4]
 [5 6 7 8]]
[1]


In [50]:
#print(np.lookfor('mean'))
#np.info(np.ndarray.dtype)

In [51]:
# Transpose `my_2d_array`
print(np.transpose(my_array))

# Or use `T` to transpose `my_2d_array`
print(my_array.T)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [52]:
# Print the shape of `x`
print(x.shape)

# Resize `x` to ((6,4))
np.resize(x, (6,4))

# Try out this as well
x.resize((6,4))

# Print out `x`
print(x)

(3, 4)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [59]:
# Print the size of `x` to see what's possible
print(x.size)

# Reshape `x` to (2,6)
#print(x.reshape((2,6)))

# Flatten `x`
z = x.ravel()

# Print `z`
print(z)

24
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
